name: Tests
on:
  pull_request:
    branches:
      - master

jobs:
  # Run tests.
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and run test container
        working-directory: frontend
        run: docker-compose --file docker-compose.test.yml up --build
      - name: Test with pytest
        run: docker-compose exec corrections python -m pytest
